defmodule Janesberry.Repo.Migrations.MigrateResources2 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:stories_authors, primary_key: false) do
      add(:story_id, :binary_id, null: true, default: nil, primary_key: true)
      add(:author_id, :binary_id, null: true, default: nil, primary_key: true)
    end

    create table(:stories, primary_key: false) do
      add(:id, :binary_id, null: false, default: nil, primary_key: true)
      add(:title, :text, null: false, default: nil, primary_key: false)
      add(:description_short, :text, null: false, default: nil, primary_key: false)
    end

    create table(:editions, primary_key: false) do
      add(:id, :binary_id, null: false, default: nil, primary_key: true)

      add(:story_id, references("stories", type: :binary_id, column: :id),
        default: nil,
        primary_key: false
      )

      add(:body, :text, null: false, default: nil, primary_key: false)
    end

    alter table("stories_authors") do
      modify(:author_id, references("persons", type: :binary_id, column: :id),
        default: nil
      )

      modify(:story_id, references("stories", type: :binary_id, column: :id),
        default: nil
      )
    end
  end

  def down() do
    alter table(:stories_authors) do
      modify(:story_id, :binary_id, null: true, default: nil, primary_key: true)
      modify(:author_id, :binary_id, null: true, default: nil, primary_key: true)
    end

    drop(table("editions"))

    drop(table("stories"))

    drop(table("stories_authors"))
  end
end
