defmodule Janesberry.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up() do
    create table(:persons, primary_key: false) do
      add(:id, :binary_id, null: false, default: nil, primary_key: true)
      add(:last_name, :text, null: false, default: nil, primary_key: false)
      add(:first_name, :text, null: false, default: nil, primary_key: false)
      add(:email, :text, null: true, default: nil, primary_key: false)
      add(:alt_name, :text, null: true, default: nil, primary_key: false)
    end
  end

  def down() do
    drop(table("persons"))
  end
end